name: "Update data/*.json"
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  update-data:
    name: Run scripts/update_data.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          ref: the-eg
          token: ${{ secrets.REPO_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run script
        run: |
          python3 scripts/update_data.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update data/*.json stats'
          default_author: github_actions
          branch: the-eg
